import Image from 'next/image'
import Link from 'next/link'
import { experiences, journal, rooms } from '@/lib/hotel-data'

const btn = 'inline-flex items-center border border-primary px-5 py-3 text-xs font-bold tracking-[.16em] text-primary transition-colors hover:bg-primary hover:text-primary-foreground'

export function RoomSection() { return <section id="stay" className="bg-background px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-6xl"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-primary">Stay awhile</p><h2 className="font-serif text-4xl leading-tight md:text-6xl">Rooms with room<br />to breathe.</h2></div><p className="max-w-sm text-muted-foreground">Five ways to settle in, each one made for long mornings, open windows and the particular pleasure of doing less.</p></div><div className="grid gap-x-5 gap-y-12 md:grid-cols-2 lg:grid-cols-3">{rooms.map((room) => <Link href={`/rooms/${room.slug}`} key={room.slug} className="group"><div className="relative aspect-[4/3] overflow-hidden"><Image src={room.image} alt={`${room.name} at The Alder House`} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-700 group-hover:scale-105" /></div><div className="flex justify-between gap-3 border-b border-border py-4"><div><h3 className="font-serif text-2xl">{room.name}</h3><p className="mt-1 text-sm text-muted-foreground">{room.size} · {room.sleeps} · {room.bed}</p></div><span className="whitespace-nowrap text-sm">From £{room.price}</span></div></Link>)}</div></div></section> }

export function DiningSection() { return <section id="dining" className="bg-primary px-5 py-24 text-primary-foreground lg:px-10 lg:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-[#d9b4a8]">From the kitchen garden</p><h2 className="font-serif text-5xl leading-[1.05] md:text-7xl">Food shaped<br />by the seasons.</h2><p className="mt-7 max-w-md text-base leading-7 text-white/75">The Orchard is our love letter to the landscape. Modern British cooking, generous and unshowy, led by what is growing in the garden and close by.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="border border-white px-5 py-3 text-xs font-bold tracking-[.16em] hover:bg-white hover:text-primary">VIEW MENUS</a><a href="#contact" className="px-5 py-3 text-xs font-bold tracking-[.16em] underline underline-offset-8">BOOK A TABLE</a></div></div><div className="relative aspect-[4/3]"><Image src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=85" alt="A candlelit table in The Orchard restaurant" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div></div><div className="mx-auto mt-24 max-w-6xl border-t border-white/25 pt-7"><div className="flex flex-col justify-between gap-5 md:flex-row"><div><p className="font-serif text-3xl">The Library Bar</p><p className="mt-2 text-sm text-white/65">Good books, good spirits, and nowhere else to be.</p></div><p className="text-sm text-white/65">Breakfast · Lunch · Dinner · Sunday lunch · Afternoon tea</p></div></div></section> }

export function SpaSection() { return <section id="spa" className="grid bg-secondary lg:grid-cols-2"><div className="relative min-h-[420px] lg:min-h-[650px]"><Image src="https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=85" alt="Quiet spa treatment room at The Bath House" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div><div className="flex flex-col justify-center px-5 py-20 lg:px-20"><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-primary">The Bath House</p><h2 className="font-serif text-5xl leading-tight md:text-6xl">A little time<br />for yourself.</h2><p className="mt-7 max-w-md text-muted-foreground">Treatment rooms, a heated outdoor pool, sauna, steam and a garden hot tub. Come for a treatment or spend the whole afternoon.</p><p className="mt-6 max-w-md text-sm text-muted-foreground">Yoga sessions · Relaxation room · Seasonal rituals</p><a href="#contact" className={`${btn} mt-9 w-fit`}>EXPLORE THE SPA</a></div></section> }

export function ExperiencesSection() { return <section id="experiences" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-6xl"><div className="mb-12 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-primary">Beyond the house</p><h2 className="font-serif text-5xl md:text-6xl">Days made<br />of small things.</h2></div><p className="max-w-sm text-muted-foreground">The best plans are often the ones that leave room for a change of mind.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{experiences.map(([name, image], i) => <div key={name} className={`group ${i === 1 ? 'md:mt-14' : i === 3 ? 'md:mt-8' : ''}`}><div className="relative aspect-[3/4] overflow-hidden"><Image src={image} alt={name} fill sizes="(max-width: 768px) 50vw, 25vw" className="object-cover transition-transform duration-700 group-hover:scale-105" /></div><p className="pt-3 font-serif text-xl">{name}</p></div>)}</div></div></section> }

export function HouseJournalSection() { return <><section id="the-house" className="bg-[#292621] px-5 py-24 text-[#f3f0e9] lg:px-10 lg:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1.1fr_1fr] lg:items-center"><div className="relative aspect-[4/5]"><Image src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85" alt="Warm, original interior details at The Alder House" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" /></div><div><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-[#d9b4a8]">The house</p><h2 className="font-serif text-5xl leading-tight md:text-6xl">A house with<br />a history.</h2><p className="mt-8 max-w-md text-white/70">Built in 1847, Alder House has always been a place for gathering. We restored its stonework, fireplaces and gardens with a light touch, keeping the character and making space for a new kind of country stay.</p><p className="mt-5 max-w-md text-white/70">There are no schedules here. Just a good breakfast, a path through the fields and someone who knows where the firewood is kept.</p><a href="#contact" className="mt-9 inline-flex border border-white px-5 py-3 text-xs font-bold tracking-[.16em] hover:bg-white hover:text-foreground">MEET THE HOUSE</a></div></div></section><section id="journal" className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-6xl"><div className="mb-12 flex items-end justify-between"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-primary">The journal</p><h2 className="font-serif text-5xl md:text-6xl">Notes from here.</h2></div><a href="#contact" className="hidden text-xs font-bold tracking-[.16em] underline underline-offset-8 md:block">VIEW ALL STORIES</a></div><div className="grid gap-7 md:grid-cols-3">{journal.map((post) => <article key={post.title}><div className="relative aspect-[4/3]"><Image src={post.image} alt={post.title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-primary">{post.category} · {post.read}</p><h3 className="mt-2 font-serif text-2xl leading-tight">{post.title}</h3><a href="#contact" className="mt-4 inline-block text-xs font-bold tracking-[.16em] underline underline-offset-8">READ STORY</a></article>)}</div></div></section></> }
